# Generated by Django 2.1.1 on 2019-03-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerList',
            fields=[
                ('AnswerId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('QuestionType', models.IntegerField(default=0)),
                ('isMust', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessList',
            fields=[
                ('AssessId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AssessName', models.CharField(max_length=50)),
                ('AssessOneDes', models.CharField(max_length=200)),
                ('AssessPro', models.IntegerField(default=0)),
                ('AssessType', models.IntegerField(default=1)),
                ('AssessDes', models.CharField(max_length=500)),
                ('AssessObject', models.CharField(max_length=300)),
                ('AssessIndexNum', models.IntegerField(default=0)),
                ('People', models.CharField(max_length=300)),
                ('AssessIndexId', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCQorMCQ', models.IntegerField(default=0)),
                ('ChoiceA', models.CharField(max_length=50)),
                ('ChoiceB', models.CharField(max_length=50)),
                ('ChoiceC', models.CharField(max_length=50)),
                ('ChoiceD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FIBAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionId', models.CharField(max_length=50)),
                ('FIBAnswer', models.CharField(max_length=100)),
                ('AnswerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.AnswerList')),
            ],
        ),
        migrations.CreateModel(
            name='HeuEvaResult',
            fields=[
                ('HeuEvaId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PlanId', models.CharField(max_length=50)),
                ('IndexId', models.CharField(max_length=50)),
                ('Interface', models.CharField(max_length=50)),
                ('HeuProblem', models.CharField(max_length=300)),
                ('SeriousDegree', models.IntegerField(default=0)),
                ('Advice', models.CharField(max_length=200, null=True)),
                ('ScreenShot', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexList',
            fields=[
                ('IndexId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IndexName', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('FamilyName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MCAList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionId', models.CharField(max_length=50)),
                ('ChoiceNum', models.IntegerField(default=1)),
                ('ChoiceAnswer', models.CharField(max_length=50)),
                ('AnswerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.AnswerList')),
            ],
        ),
        migrations.CreateModel(
            name='MethodList',
            fields=[
                ('MethodId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('MethodName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ModelList',
            fields=[
                ('ModelId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ModelType', models.IntegerField(default=1)),
                ('AssessId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('PaperId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SurveyId', models.CharField(max_length=50)),
                ('UserId', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('RecordId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ErrorRate', models.FloatField(default=0)),
                ('FinishTime', models.FloatField(default=0)),
                ('SuccessRate', models.FloatField(default=0)),
                ('LookingTime', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('PlanId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PlanName', models.CharField(max_length=59)),
                ('PlanDescription', models.CharField(max_length=500)),
                ('PlanTypeId', models.CharField(max_length=50)),
                ('AssessId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('QuestionId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('QueDescription', models.CharField(max_length=500, null=True)),
                ('QuestionType', models.IntegerField(default=0)),
                ('isMust', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScaleAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionId', models.CharField(max_length=50)),
                ('DegreeAnswer', models.IntegerField(default=1)),
                ('AnswerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.AnswerList')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeginIndex', models.CharField(max_length=50)),
                ('EndIndex', models.CharField(max_length=50)),
                ('DegreeNum', models.IntegerField(default=0)),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.QuestionList')),
            ],
        ),
        migrations.CreateModel(
            name='SCAList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionId', models.CharField(max_length=50)),
                ('ChoiceAnswer', models.CharField(max_length=5)),
                ('AnswerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.AnswerList')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyList',
            fields=[
                ('SurveyId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AssessId', models.CharField(max_length=50)),
                ('SurveyName', models.CharField(max_length=50)),
                ('SurveyPro', models.IntegerField(default=0)),
                ('SurveyQueNum', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('UserId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='questionlist',
            name='SurveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.SurveyList'),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='PlanId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.PlanList'),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.UserList'),
        ),
        migrations.AddField(
            model_name='heuevaresult',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.UserList'),
        ),
        migrations.AddField(
            model_name='choicelist',
            name='QuestionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.QuestionList'),
        ),
        migrations.AddField(
            model_name='assesslist',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.UserList'),
        ),
        migrations.AddField(
            model_name='answerlist',
            name='PaperId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.PaperList'),
        ),
    ]
