# Generated by Django 2.1.1 on 2019-03-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibanswerlist',
            name='FIBAnswer',
            field=models.CharField(max_length=1000),
        ),
    ]
