# Generated by Django 2.1.1 on 2019-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0002_auto_20190328_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlist',
            name='thisMethod',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
