# Generated by Django 2.1.1 on 2019-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0003_auto_20190317_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlist',
            name='AnswerId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assesslist',
            name='AssessId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heuevaresult',
            name='HeuEvaId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indexlist',
            name='IndexId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='methodlist',
            name='MethodId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modellist',
            name='ModelId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperlist',
            name='PaperId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='RecordId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planlist',
            name='PlanId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='QuestionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveylist',
            name='SurveyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
