# Generated by Django 2.1.1 on 2019-03-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0003_indexlist_thismethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodlist',
            name='dataSource',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='methodlist',
            name='dealData',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
