# Generated by Django 2.1.1 on 2019-03-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0004_auto_20190329_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodlist',
            name='people',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
