# Generated by Django 2.1.1 on 2019-04-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0005_methodlist_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlist',
            name='PlanDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='planlist',
            name='PlanName',
            field=models.CharField(max_length=100),
        ),
    ]
