# Generated by Django 2.1.1 on 2019-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0005_surveylist_surveyusenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesslist',
            name='AssessUseNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assesslist',
            name='AssessDes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assesslist',
            name='AssessIndexId',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assesslist',
            name='AssessObject',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='assesslist',
            name='AssessOneDes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assesslist',
            name='People',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
