# Generated by Django 2.1.1 on 2019-03-19 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0006_auto_20190318_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesslist',
            name='AssessBeginTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
