# Generated by Django 2.1.1 on 2019-03-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0007_assesslist_assessbegintime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlist',
            name='SurveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEva.SurveyList'),
        ),
    ]
